### ISSUE TITLE
Abstract away the Solana primitives

### ISSUE THREAD

**Issue by leofisG** [project-serum/serum-js#10]
Currently, the `serum-js` library still requires the developers to know the abstraction from `@solana/web3.js`, specifically `Account`, `Connection` and `PublicKey`.

However, it will be nicer if the developer doesn't need to know about these primitives and only interact with `serum-js`. And I think this should be quite easy to abstract away.

**Comment by armaniferrante** [comment]
This repository has moved to https://github.com/project-serum/serum-ts/tree/master/packages/serum. Please migrate this issue over, if desired.
