### ISSUE TITLE
Market addresses and DEX_PROGRAM_ID. for testnet/devnet

### ISSUE THREAD

**Issue by renatoshira** [project-serum/serum-js#14]
Is it possible for us to use testnet/devnet for dev purposes? In this case, are there DEX_PROGRAM_ID and markets addresses deployed there? I suppose that the market addresses are also attached to SPL mint addresses. Is it also possible to mint coins on those SPL programs?

**Comment by nishadsingh1** [comment]
Hey -- good question.

It is entirely possible to use the testnet/devnet for dev purposes. There aren't existing dex programs or markets there using the latest code, but you are very welcome to deploy them for your own use!

It's possible on both to create new SPL tokens and mint them.

You can build the DEX from source here https://github.com/project-serum/serum-dex and deploy it and markets on it to whichever nets you like.
