### ISSUE TITLE
`payer` refer to different things in `serum-js` and `crank`

### ISSUE THREAD

**Issue by leofisG** [project-serum/serum-js#19]
In `serum-js` README the `payer` is the public key address that holds the SPL token (in the case of bid order placement it will hold quote token), however, in `crank` the `payer` means the wallet account. See [here](https://github.com/project-serum/serum-dex/blob/b4140134a89d7f1f3bafd31f0808f3c95fbc12d5/crank/src/main.rs#L894).

My understanding is based on `Account` (solana-web3 type) generally correspond to `Keypair`(solana-rust-sdk).
And `PublicKey` (solana-web3 type) correspond to `Pubkey` (solana-rust-sdk).

It will be nice if the naming can be unified to avoid some confusion.

**Comment by armaniferrante** [comment]
This repository has moved to https://github.com/project-serum/serum-ts/tree/master/packages/serum. Please migrate this issue over, if desired.
