### ISSUE TITLE
Make tokens_and_markets.ts more parse friendly 

### ISSUE THREAD

**Issue by michaelhly** [project-serum/serum-js#31]
Can we load tokens_and_markets.ts from some json file?

Would like to remove this sort of parse logic from Pyserum: https://github.com/serum-community/pyserum/blob/722935cb5f4a9fdcada019c2352c166841795882/pyserum/connection.py#L9

The above logic can break easily depending on how new market pairs are added.

**Comment by nathanielparke** [comment]
This seems reasonable. I would be in favor.

**Comment by nathanielparke** [comment]
Addressed in #32

**Comment by nathanielparke** [comment]
Merged: 933a72e3077657e023773a30efb6d5be137edd5c
