### ISSUE TITLE
how much time it need to take for order show after the order placed?

### ISSUE THREAD

**Issue by gzf445** [project-serum/serum-js#35]
i have tested the market.loadOrdersForOwner and i use the postonly order.it seems that the order need about more than 15s after the order place by placeorder function.is the sol a very fast way trade?do you know the excatly time that the order to be show.and what is the meaning of cacheDurationMs in the market.loadOrdersForOwner?

**Comment by armaniferrante** [comment]
This repository has moved to https://github.com/project-serum/serum-ts/tree/master/packages/serum. Please migrate this issue over, if desired.
